#!/usr/bin/env bash
# a bash script that display to infinity and beyond indefinetly
# Display "I am invincible!!!" when receiving a SIGTERM signal
while true
do
trap 'echo "I am invincible!!!"' 15
echo "To infinity and beyond"
sleep 2
done
